language: generic

os: linux

services:
 - docker

jobs:
  include:
    - name: build and upload docker image
      before_script:
        - docker --version # print the version for logging
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      script:
        - docker build -t udagram-feed .
        - docker tag udagram-feed langerca/udagram-feed:latest
      after_success:
        - docker push langerca/udagram-feed:latest
